# Auto-generated from the Westgard/EFLM TEa database (351 analytes).
# Each entry: slug, name, matrix, TEa% (None if not specified).
EXTENDED_TEA = [
    ('ext-11-desoxycortisol', '11-Desoxycortisol', 'Serum', 27.1),
    ('ext-17-hydroxyprogesterone', '17-Hydroxyprogesterone', 'Serum', 29.7),
    ('ext-4-hydroxy-3-methoximandelate-vma', '4-hydroxy-3-methoximandelate (VMA)', 'Urine', 31.3),
    ('ext-5-nucleotidase', "5' Nucleotidase", 'Serum', 26.8),
    ('ext-5-hydroxyindolacetate-concentration', "5'-Hydroxyindolacetate, concentration", 'Urine', 26.5),
    ('ext-1-acid-glycoprotein', 'α1-Acid Glycoprotein', 'Serum', 16.2),
    ('ext-1-antichymotrypsin', 'α1-Antichymotrypsin', 'Serum', 16.8),
    ('ext-1-antitrypsin', 'α1-Antitrypsin', 'Serum', 9.2),
    ('ext-1-globulins', 'α1-Globulins', 'Serum', 15.7),
    ('ext-1-microglobulin-concentration-first-morning', 'α1-Microglobulin, concentration, first morning', 'Urine', 43.9),
    ('ext-2-antiplasmin', 'α2-Antiplasmin', 'Plasma', None),
    ('ext-2-microglobulin-output-first-morning', 'α2-Microglobulin output, first morning', 'Urine', 34.7),
    ('ext-aminobutryic-acid', 'α-aminobutryic acid', 'Plasma', 30.5),
    ('ext-amylase-pancreatic', 'α-Amylase (pancreatic)', 'Serum', 17.7),
    ('ext-amylase-pancreatic-2', 'α-Amylase (pancreatic)', 'Urine', 88.82),
    ('ext-amylase-concentration-random', 'α-Amylase concentration, random', 'Urine', 103.7),
    ('ext-carotene', 'α-Carotene', 'Plasma', 37.1),
    ('ext-carotene-2', 'α-Carotene', 'Serum', 59.8),
    ('ext-fetoprotein-non-hepatic-carcinoma', 'α-Fetoprotein(non hepatic carcinoma)', 'Serum', 21.9),
    ('ext-tocopherol', 'α-Tocopherol', 'Serum', 16.5),
    ('ext-acid-phosphatase', 'Acid phosphatase', 'Serum', 10.3),
    ('ext-acid-phosphatase-tartrate-resistant-tr-acp', 'Acid phosphatase tartrate-resistant (TR-ACP)', 'Serum', 10.5),
    ('ext-acid-phosphatase-prostatic-activity-pap', 'Acid phosphatase prostatic activity (PAP)', 'Serum', None),
    ('ext-activated-partial-thromboplastine-time', 'Activated partial thromboplastine time', 'Plasma', 4.5),
    ('ext-adiponectin', 'Adiponectin', 'Plasma', 29.1),
    ('ext-adenosine-deaminase-ada', 'Adenosine deaminase (ADA)', 'Serum', 16.7),
    ('ext-alanine', 'Alanine', 'Plasma', 26.6),
    ('ext-alanine-aminopeptidase', 'Alanine aminopeptidase', 'Serum', None),
    ('ext-alanine-aminotransferase-alt', 'Alanine aminotransferase (ALT)', 'Serum', 27.48),
    ('ext-albumin-concentration-first-morning', 'Albumin, concentration, first morning', 'Urine', 46.1),
    ('ext-albumin-output-night-urine', 'Albumin, output, night urine', 'Urine', 40.6),
    ('ext-albumin-glycated', 'Albumin, glycated', 'Serum', 7.2),
    ('ext-aldosterone', 'Aldosterone', 'Serum', 36.7),
    ('ext-aldosterone-2', 'Aldosterone', 'Urine', 46.56),
    ('ext-alkaline-phosphatase-bone', 'Alkaline phosphatase, bone', 'Serum', 14.6),
    ('ext-alkaline-phosphatase-liver', 'Alkaline phosphatase, liver', 'Serum', 15.4),
    ('ext-alkaline-phosphatase-placental', 'Alkaline phosphatase, placental', 'Serum', None),
    ('ext-ammonia-output-24h', 'Ammonia, output, 24h', 'Urine', 29.6),
    ('ext-amyloid-a', 'Amyloid A', 'Serum', 37.1),
    ('ext-androstendione', 'Androstendione', 'Serum', 23.51),
    ('ext-anion-gap', 'Anion gap', 'Serum', 11.3),
    ('ext-apolipoprotein-b', 'Apolipoprotein B', 'Serum', 11.6),
    ('ext-arginine', 'Arginine', 'Plasma', 25.7),
    ('ext-arilestearase-activity-non-inhibited', 'Arilestearase activity, non inhibited', 'Serum', 12.5),
    ('ext-ascorbate-vitamin-c', 'Ascorbate (Vitamin C)', 'Plasma', 23.8),
    ('ext-ascorbate-vitamin-c-2', 'Ascorbate (Vitamin C)', 'Serum', 31.6),
    ('ext-asparagine', 'Asparagine', 'Plasma', 17.8),
    ('ext-aspartate-aminotransferase-ast', 'Aspartate aminotransferase (AST)', 'Serum', 16.69),
    ('ext-aspartic-acid', 'Aspartic acid', 'Plasma', 41.6),
    ('ext-2-microglobulin', 'β\uf02d2-Microglobulin', 'Serum', 9.0),
    ('ext-carotene-3', 'β-Carotene', 'Plasma', 27.7),
    ('ext-carotene-4', 'β-Carotene', 'Serum', 43.1),
    ('ext-cryptoxantin', 'β-Cryptoxantin', 'Serum', None),
    ('ext-globulins', 'β-Globulins', 'Serum', 11.7),
    ('ext-base-excess', 'Base excess', 'Whole Blood', 85.0),
    ('ext-basophile-count', 'Basophile, count', 'Whole Blood', 38.5),
    ('ext-bilirubin-total', 'Bilirubin total', 'Serum', 26.94),
    ('ext-bilirubin-conjugated', 'Bilirubin conjugated', 'Serum', 44.5),
    ('ext-c-protein', 'C Protein', 'Plasma', 18.7),
    ('ext-c-reactive-protein', 'C reactive protein', 'Serum', 56.6),
    ('ext-c-reactive-protein-high-sensitivity', 'C reactive protein - high sensitivity', 'Serum', 66.54),
    ('ext-c3-complement', 'C3 Complement', 'Serum', 8.4),
    ('ext-c4-complement', 'C4 Complement', 'Serum', 16.0),
    ('ext-ca-125-antigen', 'CA 125 antigen', 'Serum', 35.4),
    ('ext-ca-15-3-antigen', 'CA 15.3 antigen', 'Serum', 20.8),
    ('ext-ca-19-9-antigen', 'CA 19.9 antigen', 'Serum', 46.03),
    ('ext-ca-549-antigen', 'CA 549 antigen', 'Serum', 16.2),
    ('ext-calcium', 'Calcium', 'Serum', 2.55),
    ('ext-calcium-complexed', 'Calcium, complexed', 'Serum', 6.1),
    ('ext-calcium-concentration-24h', 'Calcium, concentration, 24h', 'Urine', 34.1),
    ('ext-calcium-ionized', 'Calcium, ionized', 'Serum', 2.0),
    ('ext-calcium-protein-bound', 'Calcium, protein bound', 'Serum', 5.2),
    ('ext-calcium-ultrafiltrable', 'Calcium, ultrafiltrable', 'Serum', 2.7),
    ('ext-carbohydrate-deficient-transferrin', 'Carbohydrate deficient transferrin', 'Serum', 15.7),
    ('ext-carnitine-acyl-free', 'Carnitine, Acyl-free', 'Serum', 16.07),
    ('ext-carnitine-free', 'Carnitine, free', 'Serum', 11.26),
    ('ext-carnitine-total', 'Carnitine, total', 'Serum', 10.99),
    ('ext-ceruloplasmin-ferroxidase', 'Ceruloplasmin (ferroxidase)', 'Serum', 7.9),
    ('ext-cholesterol', 'Cholesterol', 'Serum', 9.01),
    ('ext-cholinesterase-concentration', 'Cholinesterase, concentration', 'Serum', None),
    ('ext-cholinesterase-activity', 'Cholinesterase, activity', 'Serum', 9.8),
    ('ext-chromogranin-a', 'Chromogranin A', 'Plasma', 17.9),
    ('ext-citrulline', 'Citrulline', 'Plasma', 29.9),
    ('ext-collagen-type-i-c-propeptide-picp', 'Collagen type I C propeptide (PICP)', 'Serum', 13.4),
    ('ext-collagen-type-i-n-propeptide-pinp', 'Collagen type I N propeptide (PINP)', 'Serum', 20.5),
    ('ext-collagen-type-iii-n-propeptide-piiinp', 'Collagen type III N propeptide (PIIINP)', 'Serum', 33.3),
    ('ext-color-first-morning', 'Color, first morning', 'Urine', 39.6),
    ('ext-copper', 'Copper', 'Plasma', 11.8),
    ('ext-copper-2', 'Copper', 'Serum', 7.47),
    ('ext-cortisol', 'Cortisol', 'Plasma', 30.66),
    ('ext-c-peptide', 'C Peptide', 'Serum', 20.8),
    ('ext-creatine-kinase-mb', 'Creatine kinase MB, %', 'Serum', 16.5),
    ('ext-creatine-kinase-mb-activity', 'Creatine kinase MB, activity', 'Serum', 24.1),
    ('ext-creatine-kinase-mb-mass', 'Creatine kinase MB, mass', 'Serum', 30.06),
    ('ext-creatinine-concentration-24h', 'Creatinine, concentration, 24h', 'Urine', 28.4),
    ('ext-creatinine-concentration-first-morning', 'Creatinine, concentration, first morning', 'Urine', 27.8),
    ('ext-creatinine-concentration-random', 'Creatinine, concentration, random', 'Urine', 42.1),
    ('ext-creatinine-output-24h', 'Creatinine, output, 24h', 'Urine', 15.4),
    ('ext-c-terminal-telopeptide-type-i-collagen-cty-i', 'C-Terminal telopeptide type I collagen (CTY I)', 'Serum', 15.45),
    ('ext-cyfra-21-1-antigen', 'Cyfra 21.1 Antigen', 'Serum', 27.9),
    ('ext-cystatin-c', 'Cystatin C', 'Plasma', None),
    ('ext-cysteine', 'Cysteine', 'Plasma', 8.3),
    ('ext-cystine', 'Cystine', 'Plasma', 47.0),
    ('ext-dehydroepiandrosterone-sulfate-dheas', 'Dehydroepiandrosterone sulfate (DHEAS)', 'Serum', 13.08),
    ('ext-deoxypyridinoline-creatinine-24h', 'Deoxypyridinoline/creatinine, 24h', 'Urine', 21.9),
    ('ext-deoxypyridinoline-creatinine-first-morning', 'Deoxypyridinoline/creatinine, first morning', 'Urine', 20.7),
    ('ext-deoxipyridinoline-minute-first-morning', 'Deoxipyridinoline/minute, first morning', 'Urine', 21.2),
    ('ext-dipeptidyl-peptidase-iv-ace', 'Dipeptidyl-peptidase IV (ACE)', 'Plasma', 10.9),
    ('ext-dipeptidyl-peptidase-iv-ace-2', 'Dipeptidyl-peptidase IV (ACE)', 'Serum', 17.9),
    ('ext-elastase', 'Elastase', 'Plasma', 15.11),
    ('ext-eosinophils-count', 'Eosinophils, count', 'Whole Blood', 37.1),
    ('ext-epinephrine', 'Epinephrine', 'Platelets', None),
    ('ext-epinephrine-2', 'Epinephrine', 'Plasma', None),
    ('ext-erythrocytes-count', 'Erythrocytes, count', 'Whole Blood', 4.4),
    ('ext-erythrocyte-distribution-wide', 'Erythrocyte distribution wide', 'Whole Blood', 4.6),
    ('ext-estradiol', 'Estradiol', 'Urine', None),
    ('ext-estradiol-2', 'Estradiol', 'Serum', 26.86),
    ('ext-estradiol-free', 'Estradiol, free', 'Serum', None),
    ('ext-estradiol-free-2', 'Estradiol, free', 'Urine', None),
    ('ext-factor-v-coagulation', 'Factor V coagulation', 'Plasma', None),
    ('ext-factor-vii-coagulation', 'Factor VII coagulation', 'Plasma', 10.7),
    ('ext-factor-viii-coagulation', 'Factor VIII coagulation', 'Plasma', 8.9),
    ('ext-factor-x-coagulation', 'Factor X coagulation', 'Plasma', None),
    ('ext-fibrinogen', 'Fibrinogen', 'Plasma', 13.6),
    ('ext-folate', 'Folate', 'Erythrocytes', 26.7),
    ('ext-folate-2', 'Folate', 'Serum', 39.0),
    ('ext-follicle-stimulating-hormone-fsh', 'Follicle stimulating hormone (FSH)', 'Serum', 21.19),
    ('ext-fructosamine', 'Fructosamine', 'Serum', 4.5),
    ('ext-galactosyl-hydroxylysine', 'Galactosyl hydroxylysine', 'Serum', 16.8),
    ('ext-fibrinogen-2', 'γ-Fibrinogen', 'Plasma', 19.3),
    ('ext-globulins-2', 'γ-Globulins', 'Serum', 16.8),
    ('ext-glutamyltransferase-ggt', 'γ-glutamyltransferase (GGT)', 'Serum', 22.11),
    ('ext-globulins-total', 'Globulins, total', 'Serum', 8.0),
    ('ext-glucose', 'Glucose', 'Plasma', 5.5),
    ('ext-glucose-6-phosphate-1-dehydrogenase-g6pdh', 'Glucose-6-phosphate-1-dehydrogenase (G6PDH)', 'Erythrocytes', 38.5),
    ('ext-glucose-6-phosphate-1-dehydrogenase-g6pdh-2', 'Glucose-6-phosphate-1-dehydrogenase (G6PDH)', 'Blood spot', 9.2),
    ('ext-glutamic-acid', 'Glutamic acid', 'Plasma', 61.4),
    ('ext-glycine', 'Glycine', 'Plasma', 20.2),
    ('ext-haptoglobin', 'Haptoglobin', 'Plasma', 25.1),
    ('ext-haptoglobin-2', 'Haptoglobin', 'Serum', 27.3),
    ('ext-hdl-1-cholesterol', 'HDL 1 cholesterol', 'Serum', 11.5),
    ('ext-hdl-2-cholesterol', 'HDL 2 cholesterol', 'Serum', 23.9),
    ('ext-hdl-3-cholesterol', 'HDL 3 cholesterol', 'Serum', 9.8),
    ('ext-hemoglobin-a1-c', 'Hemoglobin A1 C', 'Whole Blood', 3.0),
    ('ext-hemoglobin-a2', 'Hemoglobin A2', 'Whole Blood', 2.51),
    ('ext-histidine', 'Histidine', 'Plasma', 15.2),
    ('ext-homocysteine', 'Homocysteine', 'Plasma', 15.48),
    ('ext-hyaluronic-acid', 'Hyaluronic acid', 'Serum', None),
    ('ext-hydroxybutyrate-dehydrogenase', 'Hydroxybutyrate dehydrogenase', 'Serum', None),
    ('ext-hydroxyproline', 'Hydroxyproline', 'Plasma', 45.1),
    ('ext-hydroxyproline-minute-first-morning', 'Hydroxyproline/minute, first morning', 'Urine', 43.0),
    ('ext-hydroxyproline-minute-second-void', 'Hydroxyproline/minute, second void', 'Urine', 46.5),
    ('ext-immunoglobulin-a', 'Immunoglobulin A', 'Serum', 13.5),
    ('ext-immunoglobulin-g', 'Immunoglobulin G', 'Serum', 8.0),
    ('ext-immunoglobulin-m', 'Immunoglobulin M', 'Serum', 16.8),
    ('ext-immunoglobulins-chains', 'Immunoglobulins κ chains', 'Serum', 8.0),
    ('ext-immunoglobulins-chains-2', 'Immunoglobulins λ chains', 'Serum', 8.6),
    ('ext-inhibin-b', 'Inhibin B', 'Serum', 14.98),
    ('ext-insulin', 'Insulin', 'Serum', 32.9),
    ('ext-insulin-like-growth-factor-igf-1', 'Insulin-like growth factor (IGF-1)', 'Serum', 24.0),
    ('ext-insulin-like-growth-factor-binding-protein-3-igfbp-3', 'Insulin-like growth factor binding protein 3 (IGFBP-3)', 'Serum', 24.5),
    ('ext-intercellular-adhesion-molecule-1-icam-1', 'Intercellular adhesion molecule-1 (ICAM-1)', 'Serum', 6.8),
    ('ext-interferon-receptor', 'Interferon receptor', 'Leukocytes', 17.7),
    ('ext-interleukin-1', 'Interleukin 1-β', 'Serum', 36.5),
    ('ext-interleukin-8', 'Interleukin-8', 'Serum', 29.6),
    ('ext-lactate', 'Lactate', 'Whole Blood', 30.4),
    ('ext-lactate-dehydrogenase-ldh', 'Lactate dehydrogenase (LDH)', 'Serum', 11.4),
    ('ext-lactate-dehydrogenase-1-isoform-ldh1', 'Lactate dehydrogenase 1 isoform (LDH1)', 'Serum', 4.1),
    ('ext-lactate-dehydrogenase-2-isoform-ldh2', 'Lactate dehydrogenase 2 isoform (LDH2)', 'Serum', 3.7),
    ('ext-lactate-dehydrogenase-3-isoform-ldh3', 'Lactate dehydrogenase 3 isoform (LDH3)', 'Serum', 3.5),
    ('ext-lactate-dehydrogenase-4-isoform-ldh4', 'Lactate dehydrogenase 4 isoform (LDH4)', 'Serum', 6.9),
    ('ext-lactate-dehydrogenase-5-isoform-ldh5', 'Lactate dehydrogenase 5 isoform (LDH5)', 'Serum', 9.7),
    ('ext-lactoferrin', 'Lactoferrin', 'Plasma', 16.4),
    ('ext-ldl-cholesterol-oxidized', 'LDL Cholesterol (oxidized)', 'Plasma', 30.9),
    ('ext-ldl-cholesterol-small-dense', 'LDL Cholesterol, small dense', 'Serum', 13.0),
    ('ext-ldl-receptor-mrna', 'LDL receptor mRNA', 'Serum', 24.1),
    ('ext-leucine', 'Leucine', 'Plasma', 23.8),
    ('ext-leukocytes-count', 'Leukocytes count', 'Whole Blood', 15.49),
    ('ext-lipoprotein-a', 'Lipoprotein (a)', 'Serum', 24.1),
    ('ext-lutein', 'Lutein', 'Plasma', 16.9),
    ('ext-lutein-2', 'Lutein', 'Serum', None),
    ('ext-luteinizing-hormone-lh', 'Luteinizing hormone (LH)', 'Serum', 27.92),
    ('ext-lycopene', 'Lycopene', 'Plasma', 28.1),
    ('ext-lycopene-2', 'Lycopene', 'Serum', None),
    ('ext-lymphocytes-count', 'Lymphocytes, count', 'Whole Blood', 17.6),
    ('ext-lymphocytes-cd4', 'Lymphocytes CD4', 'Whole Blood', None),
    ('ext-lysine', 'Lysine', 'Plasma', 19.5),
    ('ext-magnesium', 'Magnesium', 'Erythrocytes', 7.8),
    ('ext-magnesium-2', 'Magnesium', 'Leukocytes', 20.83),
    ('ext-magnesium-3', 'Magnesium', 'Monocytes', 21.7),
    ('ext-magnesium-ionized', 'Magnesium, ionized', 'Urine', 2.9),
    ('ext-mean-corpuscular-hemoglobin-concentration-mchc', 'Mean corpuscular hemoglobin concentration (MCHC)', 'Erythrocytes', 1.27),
    ('ext-mean-corpuscular-volume-mcv', 'Mean corpuscular volume (MCV)', 'Erythrocytes', 2.42),
    ('ext-mean-platelet-volume-mpv', 'Mean platelet volume (MPV)', 'Platelets', 5.84),
    ('ext-metionine', 'Metionine', 'Plasma', 23.6),
    ('ext-monocytes-count', 'Monocytes, count', 'Whole Blood', 27.9),
    ('ext-myeloperoxidase', 'Myeloperoxidase', 'Serum', 41.4),
    ('ext-myoglobin', 'Myoglobin', 'Serum', 19.6),
    ('ext-n-acetyl-glucosaminidase-concentration-first-morning', 'N-Acetyl Glucosaminidase, concentration, first morning', 'Urine', 58.0),
    ('ext-n-acetyl-glucosaminidase-creatinine', 'N-Acetyl Glucosaminidase/Creatinine', 'Urine', 56.0),
    ('ext-neutrophyles-count', 'Neutrophyles, count', 'Whole Blood', 23.35),
    ('ext-nitrogen-output', 'Nitrogen, output', 'Urine', 18.4),
    ('ext-norepinephrine', 'Norepinephrine', 'Platelets', None),
    ('ext-norepinephrine-2', 'Norepinephrine', 'Plasma', None),
    ('ext-n-telopeptide-type-i-collagen', 'N-Telopeptide type I collagen', 'Urine', 22.95),
    ('ext-n-terminal-nt-probnp', 'N-terminal (NT)-proBNP', 'Serum', 13.0),
    ('ext-ornithine', 'Ornithine', 'Plasma', 29.7),
    ('ext-osmolality', 'Osmolality', 'Plasma', 1.6),
    ('ext-osmolality-2', 'Osmolality', 'Saliva', 17.1),
    ('ext-osmolality-3', 'Osmolality', 'Serum', 1.5),
    ('ext-osmolality-first-morning', 'Osmolality, first morning', 'Urine', 39.5),
    ('ext-osteocalcin', 'Osteocalcin', 'Serum', 13.13),
    ('ext-oxalate-concentration-24h', 'Oxalate, concentration, 24h', 'Urine', 48.2),
    ('ext-oxalate-output-24h', 'Oxalate, output, 24h', 'Urine', 46.8),
    ('ext-pco2', 'pCO2', 'Whole Blood', 5.7),
    ('ext-ph-h', 'pH [H+]', 'Whole Blood', 3.9),
    ('ext-ph-ph-units', 'pH (pH units)', 'Whole Blood', None),
    ('ext-paraoxonase-1', 'Paraoxonase 1', 'Serum', 32.3),
    ('ext-paraoxonase-1-substrate-inhibition-pon-4si', 'Paraoxonase 1 substrate inhibition (PON 4SI)', 'Serum', 23.2),
    ('ext-paraoxonase-activity-salt-stimulated', 'Paraoxonase, activity (salt stimulated)', 'Serum', 28.3),
    ('ext-parathyroid-hormone-pth', 'Parathyroid hormone (PTH)', 'Plasma', 33.43),
    ('ext-parathyroid-hormone-pth-2', 'Parathyroid hormone (PTH)', 'Serum', 30.2),
    ('ext-phosphate-output-24h', 'Phosphate, output, 24h', 'Urine', 22.1),
    ('ext-phosphate-tubular-reabsorption', 'Phosphate tubular reabsorption', 'Patient', 3.3),
    ('ext-phospholipids', 'Phospholipids', 'Serum', 8.6),
    ('ext-plasminogen', 'Plasminogen', 'Plasma', None),
    ('ext-platelets-count', 'Platelets, count', 'Whole Blood', 13.4),
    ('ext-platelet-distribution-wide', 'Platelet distribution wide', 'Whole Blood', None),
    ('ext-plateletcrit', 'Plateletcrit', 'Whole Blood', None),
    ('ext-porphobilinogen', 'Porphobilinogen', 'Urine', 22.9),
    ('ext-porphyrins-total', 'Porphyrins (total)', 'Urine', None),
    ('ext-potassium', 'Potassium', 'Leukocytes', 16.0),
    ('ext-potassium-output', 'Potassium, output', 'Urine', 28.4),
    ('ext-prealbumin', 'Prealbumin', 'Serum', 14.5),
    ('ext-pregnancy-associated-plasma-protein-a-papp-a', 'Pregnancy-associated plasma protein A (PAPP-A)', 'Serum', 15.1),
    ('ext-prolactin', 'Prolactin', 'Plasma', 51.34),
    ('ext-prolactin-2', 'Prolactin', 'Serum', 29.4),
    ('ext-proline', 'Proline', 'Plasma', 40.5),
    ('ext-prolyl-endopeptidase', 'Prolyl endopeptidase', 'Plasma', 19.3),
    ('ext-properdin-factor-b', 'Properdin factor B', 'Serum', 11.5),
    ('ext-prostatic-specific-antigen-psa', 'Prostatic specific antigen (PSA)', 'Serum', 33.6),
    ('ext-protein', 'Protein', 'Serum', 3.63),
    ('ext-protein-glycated', 'Protein, glycated', 'Serum', 3.7),
    ('ext-protein-output-24h', 'Protein, output, 24h', 'Urine', 40.0),
    ('ext-prothrombin-time', 'Prothrombin time', 'Plasma', 5.3),
    ('ext-pyridinoline', 'Pyridinoline', 'Urine', 23.6),
    ('ext-pyruvate', 'Pyruvate', 'Whole Blood', 17.5),
    ('ext-receptor-for-advanced-glycation-end-products-rage', 'Receptor for advanced glycation end- products (RAGE)', 'Serum', 26.63),
    ('ext-red-cell-distribution-wide-rdw', 'Red cell distribution wide (RDW)', 'Whole Blood', 4.6),
    ('ext-reticulocyte-highly-fluorescent-count', 'Reticulocyte highly fluorescent, count', 'Whole Blood', 24.0),
    ('ext-reticulocyte-low-fluorescent-count', 'Reticulocyte low fluorescent, count', 'Whole Blood', 2.6),
    ('ext-reticulocyte-medium-fluorescent-count', 'Reticulocyte medium fluorescent, count', 'Whole Blood', 19.6),
    ('ext-reticulocyte-count', 'Reticulocyte, count', 'Whole Blood', 16.8),
    ('ext-retinol', 'Retinol', 'Plasma', 10.6),
    ('ext-retinol-2', 'Retinol', 'Serum', 17.1),
    ('ext-rheumatoid-factor', 'Rheumatoid factor', 'Serum', 13.5),
    ('ext-scc-antigen', 'SCC antigen', 'Serum', 45.8),
    ('ext-s-protein', 'S Protein', 'Plasma', 20.7),
    ('ext-selenium', 'Selenium', 'Plasma', 14.5),
    ('ext-selenium-2', 'Selenium', 'Whole Blood', 14.1),
    ('ext-serine', 'Serine', 'Plasma', 21.7),
    ('ext-sex-hormone-binding-globulin-shbg', 'Sex hormone binding globulin (SHBG)', 'Serum', 20.42),
    ('ext-sodium', 'Sodium', 'Erythrocytes', 4.6),
    ('ext-sodium-2', 'Sodium', 'Leukocytes', 57.7),
    ('ext-sodium-bicarbonate', 'Sodium Bicarbonate', 'Whole Blood', 4.9),
    ('ext-sodium-bicarbonate-2', 'Sodium Bicarbonate', 'Serum', 5.6),
    ('ext-sodium-chloride', 'Sodium Chloride', 'Sweat', 19.7),
    ('ext-sodium-output-24-h', 'Sodium, output, 24 h.', 'Urine', 32.0),
    ('ext-soluble-cd163', 'Soluble CD163', 'Plasma', 16.7),
    ('ext-specific-gravity', 'Specific gravity', 'Urine', 0.6),
    ('ext-spermatozoa-concentration', 'Spermatozoa, concentration', 'Semen', 37.7),
    ('ext-spermatozoa-morphology', 'Spermatozoa, morphology', 'Semen', 28.2),
    ('ext-spermatozoa-progressive-motility', 'Spermatozoa, progressive motility', 'Semen', 21.6),
    ('ext-spermatozoa-fast-progressive-motility', 'Spermatozoa, fast progressive motility', 'Semen', 29.3),
    ('ext-spermatozoa-total-motility', 'Spermatozoa, total motility', 'Semen', 23.9),
    ('ext-spermatozoa-vitality', 'Spermatozoa, vitality', 'Semen', 15.4),
    ('ext-superoxide-dismutase', 'Superoxide dismutase', 'Serum', 19.1),
    ('ext-superoxide-dismutase-2', 'Superoxide dismutase', 'Erythrocytes', 13.5),
    ('ext-taurine', 'Taurine', 'Plasma', 38.6),
    ('ext-testosterone', 'Testosterone', 'Plasma', 21.07),
    ('ext-testosterone-2', 'Testosterone', 'Saliva', 22.7),
    ('ext-testosterone-3', 'Testosterone', 'Urine', None),
    ('ext-testosterone-free', 'Testosterone, free', 'Serum', None),
    ('ext-testosterone-free-2', 'Testosterone, free', 'Urine', None),
    ('ext-thyroglobulin', 'Thyroglobulin', 'Serum', 21.9),
    ('ext-thyroglobulin-antibody', 'Thyroglobulin antibody', 'Serum', 27.6),
    ('ext-thyroid-peroxidase-antibody', 'Thyroid peroxidase antibody', 'Serum', 46.2),
    ('ext-thyroid-stimulating-hormone-tsh', 'Thyroid stimulating hormone (TSH)', 'Plasma', 38.2),
    ('ext-thyroxine-t4', 'Thyroxine (T4)', 'Serum', 7.0),
    ('ext-thyroxine-free-ft4', 'Thyroxine, free (FT4)', 'Plasma', 8.74),
    ('ext-thyroxine-free-ft4-2', 'Thyroxine, free (FT4)', 'Serum', 8.0),
    ('ext-thyroxine-binding-globulin-tbg', 'Thyroxine binding globulin (TBG)', 'Serum', 0.1),
    ('ext-tirosine', 'Tirosine', 'Plasma', 24.1),
    ('ext-tissue-polypeptide-antigen-tpa', 'Tissue polypeptide antigen (TPA)', 'Serum', 43.4),
    ('ext-tissue-polypeptide-specific-antigen-tps', 'Tissue polypeptide specific antigen (TPS)', 'Serum', 58.3),
    ('ext-total-catecolamines-concentration-24h', 'Total catecolamines, concentration, 24h', 'Urine', 29.8),
    ('ext-treonine', 'Treonine', 'Plasma', 24.2),
    ('ext-triglyceride', 'Triglyceride', 'Serum', 25.99),
    ('ext-triiodothyronine-t3', 'Triiodothyronine (T3)', 'Plasma', 12.94),
    ('ext-triiodothyronine-t3-2', 'Triiodothyronine (T3)', 'Serum', 9.22),
    ('ext-triiodothyronine-free-ft3', 'Triiodothyronine, free (FT3)', 'Serum', 11.3),
    ('ext-troponin-i', 'Troponin I', 'Plasma', 76.36),
    ('ext-troponin-i-2', 'Troponin I', 'Serum', 27.91),
    ('ext-troponin-t', 'Troponin T', 'Serum', 48.9),
    ('ext-tryptophan', 'Tryptophan', 'Plasma', 57.3),
    ('ext-tumor-necrosis-factor', 'Tumor Necrosis Factor-\uf061 \uf028\uf054\uf04e\uf03c\uf044\uf02d\uf061\uf029', 'Serum', 48.4),
    ('ext-urate', 'Urate', 'Serum', 11.97),
    ('ext-urate-output-24h', 'Urate, output, 24h', 'Urine', 19.39),
    ('ext-urea', 'Urea', 'Serum', 15.55),
    ('ext-urea-output-24h', 'Urea, output, 24h', 'Urine', 22.1),
    ('ext-valine', 'Valine', 'Plasma', 19.1),
    ('ext-vanilmandelic-acid-concentration-24h', 'Vanilmandelic Acid concentration, 24h', 'Urine', 31.3),
    ('ext-vascular-cell-adhesion-molecule-1-vcam-1', 'Vascular cell adhesion molecule-1 (VCAM-1)', 'Serum', 8.5),
    ('ext-vascular-endotelial-growth-factor', 'Vascular endotelial growth factor', 'Plasma', 17.4),
    ('ext-vascular-endotelial-growth-factor-2', 'Vascular endotelial growth factor', 'Whole Blood', 19.8),
    ('ext-vascular-endotelial-growth-factor-3', 'Vascular endotelial growth factor', 'Serum', 21.0),
    ('ext-vitamin-b1', 'Vitamin B1', 'Plasma', 7.2),
    ('ext-vitamin-b2-riboflavin', 'Vitamin B2 (Riboflavin)', 'Whole Blood', 7.7),
    ('ext-vitamin-b2-riboflavin-2', 'Vitamin B2 (Riboflavin)', 'Erythrocytes', 8.5),
    ('ext-vitamin-b2-status-gluthation-reductase-activation', 'Vitamin B2 status (gluthation reductase activation)', 'Erythrocytes', 14.4),
    ('ext-vitamin-b12', 'Vitamin B12', 'Erythrocytes', 30.0),
    ('ext-vitamin-b6', 'Vitamin B6', 'Erythrocytes', 18.5),
    ('ext-vitamin-b6-2', 'Vitamin B6', 'Whole Blood', 26.4),
    ('ext-vldl-cholesterol', 'VLDL Cholesterol', 'Serum', None),
    ('ext-von-willebrand-factor', 'Von Willebrand factor', 'Plasma', 8.9),
    ('ext-water', 'Water', 'Serum', 3.3),
    ('ext-zeaxanthine', 'Zeaxanthine', 'Serum', None),
    ('ext-zinc', 'Zinc', 'Serum', 11.0),
    ('ext-zinc-2', 'Zinc', 'Plasma', 13.5),
]
